WITH QueryCPUStats AS (
  SELECT 
    pid,
    datname AS DatabaseName,
    now() - query_start AS QueryDuration,
    state,
    wait_event,
    query,
    backend_type
  FROM pg_stat_activity
  WHERE state = 'active'
)
SELECT 
  ROW_NUMBER() OVER (ORDER BY QueryDuration DESC) AS row_num,
  DatabaseName,
  pid,
  QueryDuration,
  state,
  wait_event,
  query,
  backend_type
FROM QueryCPUStats
LIMIT 25;
